### ISSUE TITLE
query: allow field names without table prefix if only one table involved

### ISSUE THREAD

**Issue by oberhamsi** [grob/ringo-sqlstore#17]
most of my queries operate on one table and it looks unnecessary verbose that I have to prefix all fields with the table

     Foo.id, Foo.title from Foo where Foo.bar > 20 and Foo.title = null;

instead of

    id, title from Foo where bar > 20 and title = null;

**Comment by grob** [comment]
i created a new [query](https://github.com/grob/ringo-sqlstore/tree/query) branch that allows queries like the above - sqlstore resolves unprefixed/unaliased properties in select clauses, aggregations et.al.

please give it a try and let me know if something doesn't work as expected. if everything works out i'm planning to create a new release short-term.

**Comment by grob** [comment]
fixed in ded80cc3dbba7cf8b317bff2e327222d37bc507e
