### ISSUE TITLE
How can we define unique field?

### ISSUE THREAD

**Issue by sclee15** [grob/ringo-sqlstore#33]
Hello?

i think ringo-sqlstore simple and awesome
but, How can we define unique field?

**Comment by grob** [comment]
Currently unique column mappings aren't supported in ringo-sqlstore, meaning you have to create the unique constraint manually in the database (sqlstore won't touch an already existing table, so it's safe to do that).

**Comment by sclee15** [comment]
thanks for a fast response!

i tried something like this for your advice
model.con.sqlQuery("ALTER TABLE Member ADD CONSTRAINT unq_member_nickname UNIQUE (nickname)");

and in run time it spits an exception
JavaException: org.postgresql.util.PSQLException: ERROR: cannot execute ALTER TABLE in a read-only transaction (ringo-sqlstore/lib/sqlstore/store.js#276)

what should i do?

thanks in advance!

**Comment by sclee15** [comment]
I found the solution and share it for those who needs this...
it is something like this

var transaction = model.store.beginTransaction();
	model.store.executeUpdate("ALTER TABLE Member ADD CONSTRAINT unq_member_nickname UNIQUE (nickname)", [], transaction);
	transaction.commit();
